name: CI/CD for Microservices
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    uses: HSM-SANOSOFT/hsm-ms-template/.github/workflows/CICD-Microservices.yml@main
    with:
      MICROSERVICE_NAME: ${{ github.event.repository.name }}
      NAMESPACE: 'app'
    secrets: 
      GHCR_PASSWORD: ${{ secrets.GHCR_PASSWORD }}
